import type { Metadata } from "next";
import {JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap', // Recommended for better performance and user experience
  variable: '--font-jetbrains-mono', // Define a CSS variable for Tailwind CSS or global use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${jetbrainsMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
